- name: cs
  color: 0e8a16
- name: algo
  color: 1d76db
- name: design
  color: fbca04
- name: net
  color: b60205
- name: db
  color: 5319e7
- name: concurrency
  color: 5319e7
- name: docs
  color: d4c5f9
- name: bench
  color: c2e0c6
- name: weekly
  color: 0052cc
- name: kpi
  color: 5319e7
- name: good first issue
  color: 7057ff
