name: ci
on:
  push:
  pull_request:
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install linters
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint version
      - name: Lint
        run: golangci-lint run ./...
      - name: Test changed modules
        env:
          BASE_REF: ${{ github.base_ref || 'main' }}
        run: make test-changed
